export default [
	" ",
	"|   <color=\"gray\">// 📚 My personal portfolio website to highlight my skills and projects.</color>",
	"|   <color=\"yellow\">Portfolio</color>                                    <link=\"https://github.com/FlorianLeChat/Portfolio\">https://github.com/FlorianLeChat/Portfolio</link>",
	" ",
	"|   <color=\"gray\">// 📖 A simple text-based RPG made in Python.</color>",
	"|   <color=\"yellow\">Python RPG</color>                                   <link=\"https://github.com/FlorianLeChat/Python-RPG\">https://github.com/FlorianLeChat/Python-RPG</link>",
	" ",
	"|   <color=\"gray\">// 📐 Calculates the size of a Workshop collection through the Steam API.</color>",
	"|   <color=\"yellow\">Steam Collection Download Size Calculator</color>    <link=\"https://github.com/FlorianLeChat/Steam-Collection-Download-Size-Calculator\">https://github.com/FlorianLeChat/Steam-Collection-Download-Size-Calculator</link>",
	" ",
	"|   <color=\"gray\">// 📊 Monitor Git commits for some Facepunch games (e.g. Rust, Garry's Mod, S&Box).</color>",
	"|   <color=\"yellow\">Facepunch Commits Monitor</color>                    <link=\"https://github.com/FlorianLeChat/Facepunch-Commits-Monitor\">https://github.com/FlorianLeChat/Facepunch-Commits-Monitor</link>",
	" ",
	"|   <color=\"gray\">// 💾 A simple, privacy-friendly, secure and high-performance file storage system.</color>",
	"|   <color=\"yellow\">Simple File Storage</color>                          <link=\"https://github.com/FlorianLeChat/Simple-File-Storage\">https://github.com/FlorianLeChat/Simple-File-Storage</link>",
	" ",
	"|   <color=\"gray\">// 🕹️ A proof-of-concept project made during my studies to manage game dedicated servers using the Source RCON protocol through a web interface.</color>",
	"|   <color=\"yellow\">Source Web Console</color>                           <link=\"https://github.com/FlorianLeChat/Source-Web-Console\">https://github.com/FlorianLeChat/Source-Web-Console</link>",
	" ",
	"|   <color=\"gray\">// 📥 A simple web page to download addons through the GmodStore API.</color>",
	"|   <color=\"yellow\">GmodStore Downloader</color>                         <link=\"https://github.com/FlorianLeChat/GmodStore-Downloader\">https://github.com/FlorianLeChat/GmodStore-Downloader</link>",
	" ",
	"|   <color=\"gray\">// 📺 A simple web page to download videos through YouTube-DL.</color>",
	"|   <color=\"yellow\">YouTube Downloader</color>                           <link=\"https://github.com/FlorianLeChat/YouTube-Downloader\">https://github.com/FlorianLeChat/YouTube-Downloader</link>",
	" ",
	"|   <color=\"gray\">// 🏗️ Domego is a serious educational game in which each player takes the role of an actor in a construction operation.</color>",
	"|   <color=\"yellow\">Domego</color>                                       <link=\"https://github.com/FlorianLeChat/Domego\">https://github.com/FlorianLeChat/Domego</link>",
	" "
];